# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_wwf_virunga.tasks.plot import (
    select_time_frequency as select_time_frequency,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    set_color_palette as set_color_palette,
)
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    extract_column_as_type as extract_column_as_type,
)
from ecoscope.platform.tasks.transformation import filter_df as filter_df

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_custom.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.transformation import (
    pivot_dataframe as pivot_dataframe,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    convert_columns_to_int as convert_columns_to_int,
)
from ecoscope_workflows_ext_mnc.tasks.transformation import (
    remove_brackets_from_column as remove_brackets_from_column,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.plot import (
    draw_bar_chart as draw_bar_chart_1,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.plot import (
    draw_grouped_line_time_series_chart as draw_grouped_line_time_series_chart,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.plot import (
    draw_time_series_bar_chart as draw_time_series_bar_chart_1,
)
from ecoscope_workflows_ext_wwf_virunga.tasks.transformation import (
    apply_cmap as apply_cmap,
)


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    time_frequency = (
        task(select_time_frequency)
        .validate()
        .set_task_instance_id("time_frequency")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_frequency") or {}))
        .call()
    )

    category_color_palette = (
        task(set_color_palette)
        .validate()
        .set_task_instance_id("category_color_palette")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            color_palette={
                "type_": "custom",
                "colors": [
                    "#1f77b4",
                    "#ff7f0e",
                    "#2ca02c",
                    "#d62728",
                    "#9467bd",
                    "#8c564b",
                    "#e377c2",
                    "#7f7f7f",
                    "#bcbd22",
                    "#17becf",
                    "#aec7e8",
                    "#ffbb78",
                    "#98df8a",
                    "#ff9896",
                    "#c5b0d5",
                    "#c49c94",
                    "#f7b6d2",
                    "#c7c7c7",
                    "#dbdb8d",
                    "#9edae5",
                ],
            },
            **(params.get("category_color_palette") or {}),
        )
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    get_events_data = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
                "created_at",
                "event_details",
                "patrols",
            ],
            event_types=[
                "balloon_landing",
                "airstrip_operations",
                "airstrip_maintenance",
                "airline_complaint",
            ],
            raise_on_empty=True,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_null_geometry=False,
            include_display_values=False,
            force_point_geometry=True,
            **(params.get("get_events_data") or {}),
        )
        .call()
    )

    extract_event_date = (
        task(extract_column_as_type)
        .validate()
        .set_task_instance_id("extract_event_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            column_name="time",
            output_type="date",
            output_column_name="date",
            **(params.get("extract_event_date") or {}),
        )
        .call()
    )

    events_temporal = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_temporal")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_event_date,
            time_col="date",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("events_temporal") or {}),
        )
        .call()
    )

    filter_balloon_events = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_balloon_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="balloon_landing",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_balloon_events") or {}),
        )
        .call()
    )

    filter_airstrip_operations = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_airstrip_operations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_operations",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_airstrip_operations") or {}),
        )
        .call()
    )

    filter_airstrip_maintenance = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airstrip_maintenance",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_airstrip_maintenance") or {}),
        )
        .call()
    )

    filter_airline_complaints = (
        task(filter_df)
        .validate()
        .set_task_instance_id("filter_airline_complaints")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="event_type",
            op="equal",
            value="airline_complaint",
            df=events_temporal,
            reset_index=False,
            **(params.get("filter_airline_complaints") or {}),
        )
        .call()
    )

    process_balloon_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_balloon_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_balloon_events,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_balloon_details") or {}),
        )
        .call()
    )

    normalize_balloon_values = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_balloon_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_balloon_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_balloon_values") or {}),
        )
        .call()
    )

    drop_balloon_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_balloon_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_balloon_values,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_balloon_prefix") or {}),
        )
        .call()
    )

    process_airstrip_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_airstrip_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_airstrip_operations,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_airstrip_details") or {}),
        )
        .call()
    )

    normalize_airstrip_op_values = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_airstrip_op_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airstrip_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_airstrip_op_values") or {}),
        )
        .call()
    )

    drop_airstrip_op_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_airstrip_op_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_airstrip_op_values,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_airstrip_op_prefix") or {}),
        )
        .call()
    )

    process_airstrip_maint_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_airstrip_maint_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_airstrip_maintenance,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_airstrip_maint_details") or {}),
        )
        .call()
    )

    normalize_airstrip_maint_vals = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_airstrip_maint_vals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airstrip_maint_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_airstrip_maint_vals") or {}),
        )
        .call()
    )

    drop_airstrip_maintenance_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_airstrip_maintenance_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_airstrip_maint_vals,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_airstrip_maintenance_prefix") or {}),
        )
        .call()
    )

    process_airline_comp_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_airline_comp_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_airline_complaints,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_airline_comp_details") or {}),
        )
        .call()
    )

    normalize_airline_comp_vals = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_airline_comp_vals")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column="event_details",
            df=process_airline_comp_details,
            skip_if_not_exists=True,
            sort_columns=True,
            **(params.get("normalize_airline_comp_vals") or {}),
        )
        .call()
    )

    drop_airline_complaint_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_airline_complaint_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_airline_comp_vals,
            prefix="event_details__",
            duplicate_strategy="keep_original",
            **(params.get("drop_airline_complaint_prefix") or {}),
        )
        .call()
    )

    map_balloon_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_balloon_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_balloon_prefix,
            drop_columns=[],
            retain_columns=[
                "date",
                "Balloon Company",
                "Where are clients staying?",
                "# of passengers",
            ],
            rename_columns={
                "Balloon Company": "balloon_company",
                "Where are clients staying?": "where_are_clients_staying",
                "# of passengers": "no_of_passengers",
            },
            raise_if_not_found=False,
            **(params.get("map_balloon_columns") or {}),
        )
        .call()
    )

    remove_balloon_brackets = (
        task(remove_brackets_from_column)
        .validate()
        .set_task_instance_id("remove_balloon_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_balloon_columns,
            columns=["balloon_company", "where_are_clients_staying"],
            **(params.get("remove_balloon_brackets") or {}),
        )
        .call()
    )

    rename_balloon_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_balloon_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_balloon_brackets,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "date": "Date",
                "balloon_company": "Balloon Company",
                "where_are_clients_staying": "Where Are Clients Staying",
                "no_of_passengers": "No Of Passengers",
            },
            raise_if_not_found=False,
            **(params.get("rename_balloon_display") or {}),
        )
        .call()
    )

    balloon_company_colors = (
        task(apply_cmap)
        .validate()
        .set_task_instance_id("balloon_company_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_balloon_brackets,
            input_column_name="balloon_company",
            color_palette=category_color_palette,
            output_column_name="balloon_company_colors",
            color_format="rgba_tuple",
            alpha=1.0,
            **(params.get("balloon_company_colors") or {}),
        )
        .call()
    )

    persist_balloon_landing = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_balloon_landing")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_balloon_display,
            filename="balloon_landing_summary_table",
            **(params.get("persist_balloon_landing") or {}),
        )
        .call()
    )

    balloon_landing_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("balloon_landing_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_balloon_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Balloon Landing Summary",
            **(params.get("balloon_landing_table_html") or {}),
        )
        .call()
    )

    balloon_landing_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("balloon_landing_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="balloon_landing_summary_table.html",
            text=balloon_landing_table_html,
            **(params.get("balloon_landing_table_html_url") or {}),
        )
        .call()
    )

    balloon_landing_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("balloon_landing_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Balloon Landing Summary",
            data=balloon_landing_table_html_url,
            **(params.get("balloon_landing_table_widget") or {}),
        )
        .call()
    )

    balloon_pax_chart = (
        task(draw_grouped_line_time_series_chart)
        .validate()
        .set_task_instance_id("balloon_pax_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=balloon_company_colors,
            x_axis="date",
            y_axis="no_of_passengers",
            group_column="balloon_company",
            agg_function="sum",
            time_frequency=time_frequency,
            group_order=None,
            fill=False,
            ascending=False,
            color_column="balloon_company_colors",
            plot_style=None,
            line_style=None,
            widget_id=None,
            layout_style={
                "font_size": 10,
                "plot_bgcolor": "#f5f5f5",
                "font_color": None,
                "font_style": None,
                "showlegend": True,
                "legend_title": None,
                "title": None,
                "title_x": 0.5,
                "title_y": 0.95,
                "xaxis": {"title": "Date"},
                "yaxis": {"title": "Passengers"},
            },
            **(params.get("balloon_pax_chart") or {}),
        )
        .call()
    )

    balloon_pax_chart_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("balloon_pax_chart_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="balloon_pax_chart",
            text=balloon_pax_chart,
            **(params.get("balloon_pax_chart_html_url") or {}),
        )
        .call()
    )

    balloon_pax_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("balloon_pax_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Balloon Passengers Over Time",
            data=balloon_pax_chart_html_url,
            **(params.get("balloon_pax_chart_widget") or {}),
        )
        .call()
    )

    balloon_lodge_chart = (
        task(draw_bar_chart_1)
        .validate()
        .set_task_instance_id("balloon_lodge_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=balloon_company_colors,
            category="where_are_clients_staying",
            mode="stacked",
            y_axis="no_of_passengers",
            stack_column="balloon_company",
            agg_function="sum",
            ascending=True,
            widget_id=None,
            color_column="balloon_company_colors",
            plot_style={"xperiodalignment": "middle"},
            overlay_opacity=0.6,
            category_order=None,
            stack_order=None,
            bar_chart_configs=None,
            layout_style={
                "bargap": 0.05,
                "bargroupgap": 0.05,
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "font_size": 10,
                "font_color": "#222222",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {"title": "Where clients are staying"},
                "yaxis": {"title": "Passengers"},
            },
            **(params.get("balloon_lodge_chart") or {}),
        )
        .call()
    )

    balloon_lodge_chart_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("balloon_lodge_chart_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="balloon_lodge_chart",
            text=balloon_lodge_chart,
            **(params.get("balloon_lodge_chart_html_url") or {}),
        )
        .call()
    )

    balloon_lodge_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("balloon_lodge_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Balloon Passengers by Lodge",
            data=balloon_lodge_chart_html_url,
            **(params.get("balloon_lodge_chart_widget") or {}),
        )
        .call()
    )

    map_airstrip_op_columns = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_airstrip_op_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_airstrip_op_prefix,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "Airline": "airline",
                "Arrival or departure": "arrival_departure",
                "Attendant": "attendant",
                "Camp/Lodge": "camp_lodge",
                "Number of clients": "no_of_clients",
            },
            raise_if_not_found=False,
            **(params.get("map_airstrip_op_columns") or {}),
        )
        .call()
    )

    remove_airstrip_op_brackets = (
        task(remove_brackets_from_column)
        .validate()
        .set_task_instance_id("remove_airstrip_op_brackets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_airstrip_op_columns,
            columns=["airline", "arrival_departure", "attendant", "camp_lodge"],
            **(params.get("remove_airstrip_op_brackets") or {}),
        )
        .call()
    )

    convert_airstrip_op_ints = (
        task(convert_columns_to_int)
        .validate()
        .set_task_instance_id("convert_airstrip_op_ints")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=remove_airstrip_op_brackets,
            columns=["no_of_clients"],
            errors="coerce",
            fill_value=0,
            **(params.get("convert_airstrip_op_ints") or {}),
        )
        .call()
    )

    airstrip_op_summary_table = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("airstrip_op_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_airstrip_op_ints,
            groupby_cols=["camp_lodge", "arrival_departure"],
            summary_params=[
                {
                    "display_name": "no_of_clients",
                    "aggregator": "sum",
                    "column": "no_of_clients",
                    "decimal_places": 0,
                }
            ],
            reset_index=True,
            **(params.get("airstrip_op_summary_table") or {}),
        )
        .call()
    )

    pivot_airstrip_ops = (
        task(pivot_dataframe)
        .validate()
        .set_task_instance_id("pivot_airstrip_ops")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=airstrip_op_summary_table,
            index="camp_lodge",
            columns=["arrival_departure"],
            values=["no_of_clients"],
            fill_value=0,
            **(params.get("pivot_airstrip_ops") or {}),
        )
        .call()
    )

    convert_pivot_int = (
        task(convert_columns_to_int)
        .validate()
        .set_task_instance_id("convert_pivot_int")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pivot_airstrip_ops,
            columns=["arrival", "departure"],
            errors="coerce",
            fill_value=0,
            **(params.get("convert_pivot_int") or {}),
        )
        .call()
    )

    rename_airstrip_op_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_airstrip_op_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_pivot_int,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "camp_lodge": "Camp Lodge",
                "no_of_clients_Arrival": "Arrival",
                "no_of_clients_Departure": "Departure",
            },
            raise_if_not_found=False,
            **(params.get("rename_airstrip_op_display") or {}),
        )
        .call()
    )

    airstrip_direction_colors = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("airstrip_direction_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_airstrip_op_ints,
            input_column_name="arrival_departure",
            output_column_name="arrival_departure_colors",
            colormap={"Arrival": "#1f77b4", "Departure": "#ff7f0e"},
            **(params.get("airstrip_direction_colors") or {}),
        )
        .call()
    )

    persist_airstrip_operations = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_airstrip_operations")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_airstrip_op_display,
            filename="airstrip_operations_summary_table",
            **(params.get("persist_airstrip_operations") or {}),
        )
        .call()
    )

    airstrip_op_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("airstrip_op_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_airstrip_op_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Airstrip Operations Summary",
            **(params.get("airstrip_op_table_html") or {}),
        )
        .call()
    )

    airstrip_op_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("airstrip_op_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="airstrip_operations_summary_table.html",
            text=airstrip_op_table_html,
            **(params.get("airstrip_op_table_html_url") or {}),
        )
        .call()
    )

    airstrip_op_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("airstrip_op_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Airstrip Operations Summary",
            data=airstrip_op_table_html_url,
            **(params.get("airstrip_op_table_widget") or {}),
        )
        .call()
    )

    airstrip_clients_chart = (
        task(draw_grouped_line_time_series_chart)
        .validate()
        .set_task_instance_id("airstrip_clients_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=airstrip_direction_colors,
            x_axis="date",
            y_axis="no_of_clients",
            group_column="arrival_departure",
            agg_function="sum",
            time_frequency=time_frequency,
            group_order=None,
            fill=False,
            ascending=False,
            color_column="arrival_departure_colors",
            plot_style=None,
            line_style=None,
            widget_id=None,
            layout_style={
                "font_size": 10,
                "plot_bgcolor": "#f5f5f5",
                "font_color": None,
                "font_style": None,
                "showlegend": True,
                "legend_title": None,
                "title": None,
                "title_x": 0.5,
                "title_y": 0.95,
                "xaxis": {"title": "Date"},
                "yaxis": {"title": "Clients"},
            },
            **(params.get("airstrip_clients_chart") or {}),
        )
        .call()
    )

    airstrip_clients_chart_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("airstrip_clients_chart_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="airstrip_clients_chart",
            text=airstrip_clients_chart,
            **(params.get("airstrip_clients_chart_html_url") or {}),
        )
        .call()
    )

    airstrip_clients_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("airstrip_clients_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Airstrip Clients Over Time",
            data=airstrip_clients_chart_html_url,
            **(params.get("airstrip_clients_chart_widget") or {}),
        )
        .call()
    )

    airstrip_lodge_chart = (
        task(draw_bar_chart_1)
        .validate()
        .set_task_instance_id("airstrip_lodge_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_airstrip_op_display,
            category="Camp Lodge",
            mode="grouped",
            bar_chart_configs=[
                {
                    "column": "Arrival",
                    "agg_func": "sum",
                    "label": "Arrival",
                    "show_label": False,
                    "style": {"marker_color": "#1f77b4"},
                },
                {
                    "column": "Departure",
                    "agg_func": "sum",
                    "label": "Departure",
                    "show_label": False,
                    "style": {"marker_color": "#ff7f0e"},
                },
            ],
            y_axis=None,
            stack_column=None,
            agg_function=None,
            ascending=True,
            widget_id=None,
            color_column=None,
            plot_style=None,
            overlay_opacity=0.6,
            category_order=None,
            stack_order=None,
            layout_style={
                "bargap": 0.05,
                "bargroupgap": 0.05,
                "title": None,
                "title_x": 0.01,
                "title_y": 0.95,
                "showlegend": True,
                "font_size": 10,
                "font_color": "#222222",
                "plot_bgcolor": "#f5f5f5",
                "xaxis": {"title": "Camp/Lodge"},
                "yaxis": {"title": "Clients"},
            },
            **(params.get("airstrip_lodge_chart") or {}),
        )
        .call()
    )

    airstrip_lodge_chart_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("airstrip_lodge_chart_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="airstrip_lodge_chart",
            text=airstrip_lodge_chart,
            **(params.get("airstrip_lodge_chart_html_url") or {}),
        )
        .call()
    )

    airstrip_lodge_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("airstrip_lodge_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Airstrip Clients by Camp/Lodge",
            data=airstrip_lodge_chart_html_url,
            **(params.get("airstrip_lodge_chart_widget") or {}),
        )
        .call()
    )

    map_airstrip_maintenance = (
        task(map_columns)
        .validate()
        .set_task_instance_id("map_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_airstrip_maintenance_prefix,
            drop_columns=[],
            retain_columns=["date", "Maintenance type"],
            rename_columns={"Maintenance type": "maintenance_type"},
            raise_if_not_found=False,
            **(params.get("map_airstrip_maintenance") or {}),
        )
        .call()
    )

    rename_airstrip_maint_display = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_airstrip_maint_display")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_airstrip_maintenance,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"date": "Date", "maintenance_type": "Maintenance Type"},
            raise_if_not_found=False,
            **(params.get("rename_airstrip_maint_display") or {}),
        )
        .call()
    )

    maintenance_type_colors = (
        task(apply_cmap)
        .validate()
        .set_task_instance_id("maintenance_type_colors")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=map_airstrip_maintenance,
            input_column_name="maintenance_type",
            color_palette=category_color_palette,
            output_column_name="maintenance_type_colors",
            color_format="rgba_tuple",
            alpha=1.0,
            **(params.get("maintenance_type_colors") or {}),
        )
        .call()
    )

    persist_airstrip_maintenance = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_airstrip_maintenance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            df=rename_airstrip_maint_display,
            filename="airstrip_maintenance_summary_table",
            **(params.get("persist_airstrip_maintenance") or {}),
        )
        .call()
    )

    airstrip_maintenance_table_html = (
        task(draw_table)
        .validate()
        .set_task_instance_id("airstrip_maintenance_table_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=rename_airstrip_maint_display,
            columns=None,
            table_config={
                "enable_sorting": True,
                "enable_filtering": True,
                "enable_download": False,
                "hide_header": False,
            },
            widget_id="Airstrip Maintenance Summary",
            **(params.get("airstrip_maintenance_table_html") or {}),
        )
        .call()
    )

    airstrip_maint_table_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("airstrip_maint_table_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="airstrip_maintenance_summary_table.html",
            text=airstrip_maintenance_table_html,
            **(params.get("airstrip_maint_table_html_url") or {}),
        )
        .call()
    )

    airstrip_maint_table_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("airstrip_maint_table_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Airstrip Maintenance Summary",
            data=airstrip_maint_table_html_url,
            **(params.get("airstrip_maint_table_widget") or {}),
        )
        .call()
    )

    airstrip_maint_chart = (
        task(draw_time_series_bar_chart_1)
        .validate()
        .set_task_instance_id("airstrip_maint_chart")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            dataframe=maintenance_type_colors,
            x_axis="date",
            y_axis="date",
            category="maintenance_type",
            agg_function="count",
            time_frequency=time_frequency,
            color_column="maintenance_type_colors",
            plot_style=None,
            widget_id=None,
            layout_style={
                "font_size": 10,
                "plot_bgcolor": "#f5f5f5",
                "font_color": None,
                "font_style": None,
                "showlegend": True,
                "legend_title": None,
                "title": None,
                "title_x": 0.5,
                "title_y": 0.95,
                "xaxis": {"title": "Date"},
                "yaxis": {"title": "Maintenance events"},
            },
            **(params.get("airstrip_maint_chart") or {}),
        )
        .call()
    )

    airstrip_maint_chart_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("airstrip_maint_chart_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            filename_suffix="airstrip_maint_chart",
            text=airstrip_maint_chart,
            **(params.get("airstrip_maint_chart_html_url") or {}),
        )
        .call()
    )

    airstrip_maint_chart_widget = (
        task(create_plot_widget_single_view)
        .validate()
        .set_task_instance_id("airstrip_maint_chart_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Airstrip Maintenance Over Time",
            data=airstrip_maint_chart_html_url,
            **(params.get("airstrip_maint_chart_widget") or {}),
        )
        .call()
    )

    logistics_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("logistics_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                balloon_pax_chart_widget,
                balloon_lodge_chart_widget,
                balloon_landing_table_widget,
                airstrip_clients_chart_widget,
                airstrip_lodge_chart_widget,
                airstrip_op_table_widget,
                airstrip_maint_chart_widget,
                airstrip_maint_table_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("logistics_dashboard") or {}),
        )
        .call()
    )

    return logistics_dashboard
